const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('deskLibrary', {
  getInitialData: () => ipcRenderer.invoke('get-initial-data'),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  resetSettings: () => ipcRenderer.invoke('reset-settings'),
  createManualTextRecord: (text) => ipcRenderer.invoke('create-manual-text-record', text),
  updateRecordContent: (payload) => ipcRenderer.invoke('update-record-content', payload),
  updateRecordNote: (payload) => ipcRenderer.invoke('update-record-note', payload),
  deleteRecord: (id) => ipcRenderer.invoke('delete-record', id),
  deleteRecords: (ids) => ipcRenderer.invoke('delete-records', ids),
  moveRecordToCommon: (id) => ipcRenderer.invoke('move-record-to-common', id),
  moveRecordToDaily: (id) => ipcRenderer.invoke('move-record-to-daily', id),
  openImagePath: (imagePath) => ipcRenderer.invoke('open-image-path', imagePath),
  copyRecordContent: (id) => ipcRenderer.invoke('copy-record-content', id),
  selectAssetFiles: () => ipcRenderer.invoke('select-asset-files'),
  selectAssetFolders: () => ipcRenderer.invoke('select-asset-folders'),
  selectFolder: () => ipcRenderer.invoke('select-folder'),
  selectFloatingIconFile: () => ipcRenderer.invoke('select-floating-icon-file'),
  importAssets: (payload) => ipcRenderer.invoke('import-assets', payload),
  updateAssetNote: (payload) => ipcRenderer.invoke('update-asset-note', payload),
  openAssetPrimary: (id) => ipcRenderer.invoke('open-asset-primary', id),
  openAssetSource: (id) => ipcRenderer.invoke('open-asset-source', id),
  openAssetLocation: (id) => ipcRenderer.invoke('open-asset-location', id),
  openAssetStored: (id) => ipcRenderer.invoke('open-asset-stored', id),
  openAssetStoredLocation: (id) => ipcRenderer.invoke('open-asset-stored-location', id),
  deleteAsset: (id) => ipcRenderer.invoke('delete-asset', id),
  scanBrowserCards: (payload) => ipcRenderer.invoke('scan-browser-cards', payload),
  importBrowserCards: (payload) => ipcRenderer.invoke('import-browser-cards', payload),
  listOnlineImportTargets: () => ipcRenderer.invoke('list-online-import-targets'),
  runOnlineImport: (payload) => ipcRenderer.invoke('run-online-import', payload),
  updateBrowserCard: (payload) => ipcRenderer.invoke('update-browser-card', payload),
  refreshBrowserCardCookies: (id) => ipcRenderer.invoke('refresh-browser-card-cookies', id),
  rewriteBrowserCardCookies: (id) => ipcRenderer.invoke('rewrite-browser-card-cookies', id),
  openBrowserCard: (id) => ipcRenderer.invoke('open-browser-card', id),
  injectBrowserCard: (id) => ipcRenderer.invoke('inject-browser-card', id),
  getBrowserInjectTargets: () => ipcRenderer.invoke('get-browser-inject-targets'),
  executeBrowserCardInject: (payload) => ipcRenderer.invoke('execute-browser-card-inject', payload),
  openBrowserCardSource: (id) => ipcRenderer.invoke('open-browser-card-source', id),
  getBrowserImportSources: (payload) => ipcRenderer.invoke('get-browser-import-sources', payload),
  getSelfBuiltImportSources: (payload) => ipcRenderer.invoke('get-self-built-import-sources', payload),
  openSelfBuiltBrowser: (payload) => ipcRenderer.invoke('open-self-built-browser', payload),
  loadBrowserImportGroups: (payload) => ipcRenderer.invoke('load-browser-import-groups', payload),
  buildBrowserImportCards: (payload) => ipcRenderer.invoke('build-browser-import-cards', payload),
  deleteBrowserCard: (id) => ipcRenderer.invoke('delete-browser-card', id),
  deleteBrowserCards: (ids) => ipcRenderer.invoke('delete-browser-cards', ids),
  checkBrowserCardConnectivity: (ids) => ipcRenderer.invoke('check-browser-card-connectivity', ids),
  openMainWindow: () => ipcRenderer.invoke('open-main-window'),
  openMainWindowPage: (page) => ipcRenderer.invoke('open-main-window-page', page),
  minimizeWindow: () => ipcRenderer.invoke('window-minimize'),
  toggleMaximizeWindow: () => ipcRenderer.invoke('window-toggle-maximize'),
  closeWindow: () => ipcRenderer.invoke('window-close'),
  openExternalUrl: (url) => ipcRenderer.invoke('open-external-url', url),
  onSnapshot: (callback) => ipcRenderer.on('snapshot', (_, payload) => callback(payload)),
  onNavigatePage: (callback) => ipcRenderer.on('navigate-page', (_, payload) => callback(payload)),
  onOpenRecordDetail: (callback) => ipcRenderer.on('open-record-detail', (_, payload) => callback(payload))
});
